# Generated by Django 5.0.7 on 2024-07-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=354)),
                ('token', models.TextField()),
            ],
            options={
                'verbose_name': 'AdminUser',
                'verbose_name_plural': 'AdminUsers',
            },
        ),
    ]
