# Generated by Django 4.2.6 on 2024-07-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
