# Generated by Django 4.2.6 on 2024-07-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
