# Generated by Django 4.2.6 on 2024-07-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_withdawal_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
