# Generated by Django 4.2.6 on 2024-07-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdawal',
            name='address',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
