# Generated by Django 4.2.6 on 2024-07-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_withdawal_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Withdawal',
            new_name='Withdrawal',
        ),
    ]
