# Generated by Django 4.2.6 on 2024-07-08 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='approved',
        ),
        migrations.AddField(
            model_name='deposit',
            name='name',
            field=models.CharField(default='Depost', max_length=50),
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transaction', to='core.transaction'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='name',
            field=models.CharField(default='Withdraw', max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_transaction', to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=50),
        ),
    ]
