# Generated by Django 5.0.7 on 2024-07-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_adminplans_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminplans',
            name='features',
            field=models.TextField(default='NO features'),
            preserve_default=False,
        ),
    ]
