# Generated by Django 5.0.7 on 2024-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_adminplans_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ref_by",
            field=models.CharField(blank=True, default="", max_length=120, null=True),
        ),
    ]
